site_name: BotCity Plugins - Python
copyright: BotCity &copy; - All rights reserved

nav:
    - Home: index.md
    - Plugins:
      - Amazon AWS:
        - S3: '!include ./bot-aws-s3-plugin-python/mkdocs.yml'
        - Lambda: '!include ./bot-aws-lambda-plugin-python/mkdocs.yml'
      - Google:
        - Gmail: '!include ./bot-gmail-plugin-python/mkdocs.yml'
        - Google Cloud Vision: '!include ./bot-cloudvision-plugin-python/mkdocs.yml'
        - Google Drive: '!include ./bot-googledrive-plugin-python/mkdocs.yml'
        - Google Sheets: '!include ./bot-googlesheets-plugin-python/mkdocs.yml'
      - Microsoft Office:
        - Excel: '!include ./bot-excel-plugin-python/mkdocs.yml'
      - Captcha: '!include ./bot-captcha-plugin-python/mkdocs.yml'
      - Crawler: '!include ./bot-crawler-plugin-python/mkdocs.yml'
      - CSV: '!include ./bot-csv-plugin-python/mkdocs.yml'
      - Discord: '!include ./bot-discord-plugin-python/mkdocs.yml'
      - Email: '!include ./bot-email-plugin-python/mkdocs.yml'
      - FTP/SFTP: '!include ./bot-ftp-plugin-python/mkdocs.yml'
      - Http: '!include ./bot-http-plugin-python/mkdocs.yml'
    - Utils: '!include ./botcity-utils-python/mkdocs.yml'

theme:
  icon:
    repo: fontawesome/brands/bitbucket
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/botcity-dev/botcity-plugins-python.git
      name: BotCity Plugins - Python -> GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/botcitydev
      name: BotCity on Twitter
  analytics:
    provider: google
    property: UA-203228041-1

plugins:
    - monorepo
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            selection:
              inherited_members: false
              filters:
                - "!^_"  # exclude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
                - "!([a-z])*([A-Z])" # exclude camelCase elements
            rendering:
              show_source: false
              show_root_heading: true
