name: Publish Documentation

on:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.repository == 'botcity-dev/botcity-plugins-python' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python -m pip install --upgrade pip
      - name: Build Docs
        run: |
          ./build.sh
      - name: Debug
        run: |
          echo "Debugging..."
          ls -la
      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site/
